import type { OnlineMapVehicle } from './types';

// Демонстрационные данные изолированы от будущего потока телеметрии.
export const onlineMapVehicles = [
  {
    id: 'lada-vesta-a123mr77',
    name: 'Lada Vesta',
    plate: 'А 123 МР 77',
    status: 'moving',
    longitude: 92.8727,
    latitude: 56.0106,
    speedKph: 48,
    fuelPercent: 72,
    lastSeenLabel: 'только что',
    address: 'Красноярск, ул. Карла Маркса',
  },
  {
    id: 'haval-jolion-v456kh178',
    name: 'Haval Jolion',
    plate: 'В 456 КХ 178',
    status: 'idle',
    longitude: 92.8794,
    latitude: 56.0194,
    speedKph: 0,
    fuelPercent: 58,
    lastSeenLabel: '3 минуты назад',
    address: 'Красноярск, проспект Мира',
  },
  {
    id: 'geely-atlas-e789no77',
    name: 'Geely Atlas',
    plate: 'Е 789 НО 77',
    status: 'moving',
    longitude: 92.8568,
    latitude: 56.0321,
    speedKph: 61,
    fuelPercent: 84,
    lastSeenLabel: 'только что',
    address: 'Красноярск, ул. Высотная',
  },
  {
    id: 'kia-k5-k111mr199',
    name: 'Kia K5',
    plate: 'К 111 МР 199',
    status: 'offline',
    longitude: 92.8211,
    latitude: 55.9889,
    speedKph: 0,
    fuelPercent: 31,
    lastSeenLabel: '18 минут назад',
    address: 'Красноярск, ул. 60 лет Октября',
  },
  {
    id: 'changan-uni-k-m333ah750',
    name: 'Changan UNI-K',
    plate: 'М 333 АХ 750',
    status: 'idle',
    longitude: 92.9125,
    latitude: 56.0058,
    speedKph: 0,
    fuelPercent: 46,
    lastSeenLabel: '7 минут назад',
    address: 'Красноярск, ул. Молокова',
  },
] satisfies readonly OnlineMapVehicle[];
